# Generated by Django 5.1.2 on 2024-11-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
