# Generated by Django 5.1.2 on 2024-11-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_alert_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="is_deleted",
        ),
    ]
