# Generated by Django 5.1.2 on 2024-11-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0004_remove_alert_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="board_id",
            field=models.IntegerField(default=0),
        ),
    ]
