# Generated by Django 5.1.2 on 2024-12-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0005_alert_board_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="msg",
        ),
    ]
