# Generated by Django 5.1.2 on 2024-12-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0006_remove_alert_msg"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="distance1",
            field=models.IntegerField(default=0),
        ),
    ]
