# Generated by Django 5.1.2 on 2024-12-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0007_alert_distance1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="distance1",
        ),
    ]
