# Generated by Django 5.1.2 on 2024-12-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0009_alert_distance1"),
    ]

    operations = [
       
        migrations.AddField(
            model_name="alert",
            name="status",
            field=models.CharField(default="active", max_length=50),
        ),
    ]
