# Generated by Django 5.1.2 on 2024-12-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0010_remove_alert_distance1_alert_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="distance1",
        ),
    ]
