# Generated by Django 5.1.2 on 2024-12-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0011_remove_alert_distance1"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnimalPosition",
        ),
    ]
