# Generated by Django 5.1.2 on 2024-12-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0013_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
    ]
