# Generated by Django 5.1.2 on 2024-12-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0014_alert_is_processed"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board_id", models.IntegerField()),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
